import { DynamicServerError } from "next/dist/client/components/hooks-server-context";
import Head from "next/head";

export default function Volunteer() {
  return (
    <>
      <Head>
        <title>Volunteer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Volunteer</h1>
        </div>
      </main>
    </>
  );
}
