import Head from "next/head";
import styles from "@/styles/Home.module.css";
import circles from "@/assets/circles.svg";
import christmas from "@/assets/display_christmas_evt.svg";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Image className={styles.circles} src={circles} alt="background graphics" width={2196} height={1356} />
        <div className={styles.description}>
          <h1>Empowering collective action through shared experiences.</h1>
        </div>
        <a href="#" className="link">
          Join the event
        </a>
        <Image className={styles.christmas} src={christmas} alt="background graphics" width={1365.9} height={395.21} />
        <div className={styles.upcoming}>
          <h4 className="label">Upcoming event</h4>
          <div className="divider"></div>
          <h5 className="highlighted">11th December / 18:00 - 22:00</h5>
          <p>Lorem ipsum dolor sit amet consectetur adipiscing eli mattis sit phasellus mollis sit aliquam sit nullam.</p>
          <div className={styles.buttonsflex}>
            <a href="#" className="link">
              Join the event
            </a>
            <a href="#" className="link">
              Learn more
            </a>
          </div>
        </div>
        <button>This is a button</button>
      </main>
    </>
  );
}
